## Static configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true  # Enable the dashboard without authentication
  dashboard: true

entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

# Disable SSL/TLS since it's not required
# accessLog: {}
# log:
#   level: INFO
